apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gitlab-repo-template
  title: GitLab Repository Template
  description: Creates a new GitLab repository from a template
spec:
  owner: nickngch
  type: service

  parameters:
    - title: Fill in basic information
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        description:
          title: Description
          type: string
          description: Description of the component
        targetPath:
          title: Target Path in repo
          type: string
          description: Name of the directory to create in the repository
        branchName:
          title: Destination Branch Name
          type: string
          description: Name of the branch to create in the repository
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.com
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
    - title: Kubernetes Resources
      properties:
        volume_type:
          title: Resource Type
          type: string
          description: The Kubernetes resource to be created
          enum:
            - deploy
            - svc
            - ing
          enumNames:
            - 'Deployment'
            - 'Service'
            - 'Ingress'
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./template
        targetPath: ${{ parameters.targetPath }}
        values:
          name: ${{parameters.name}}
    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: Creating catalog-info.yaml ${{ parameters.name }} for backstage
        branchName: ${{ parameters.branchName }}
        description: |
          # New project: ${{ parameters.name }}
          ${{ parameters.description if parameters.description }}
        targetPath: ${{ parameters.targetPath if parameters.targetPath else '.' }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        commitAction: create